# Generated by Django 5.1.6 on 2025-03-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_moeda_atual',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_moeda_convertida',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_moeda_para_conversao',
            field=models.CharField(max_length=200),
        ),
    ]
